# SE2_data_processing

In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

In [16]:
# Paths 
raw_dir = Path.home()/"data"/"raw"
processed_dir = Path.home()/"data"/"processed"
processed_dir.mkdir(parents=True, exist_ok=True)

# Input file from SE1
raw_file = raw_dir/"MPs_WWTPs_Eff_DUMMY.csv"

# Load data
df = pd.read_csv(raw_file)

df.head()

,WWTP / Env.,Municipality,Date,Sampling Point,Project,Monitoring Interval,Season,WWTP,Tech type,PE,...,Sucralose,Sulfapyridine,Telmisartan,Tramadol,Trimetoprim,Valsartan,Valsartan acid,Venlafaxine,Venlafaxine O-desmethyl,Total_Concentration_ngL
0,Site 1,City 1,10/4/2024 0:00,CAS_S1_5,Project XXXX,Seasonally,Fall 2024,WWTP 1A,CAS,21480.46,...,45860.97,2452.33,2026.55,114.35,349.61,4770.29,77.81,655.26,1369.85,298065.0
1,Site 1,City 1,10/30/2024 0:00,MBR_S1_7,Project XXXX,Seasonally,Fall 2024,WWTP 1B,MBR,80391.15,...,54066.31,661.41,2089.36,312.34,269.15,12647.16,1283.40,512.79,1139.59,173127.7
2,Site 2,City 2,11/5/2024 0:00,Post_S2_5,Project XXXX,Seasonally,Fall 2024,WWTP 2,CAS,12607.66,...,48321.51,2198.68,1599.23,347.75,382.38,3290.60,1229.50,440.15,2203.82,247389.0
3,Site 3,City 3,11/12/2024 0:00,Post_S3_5,Project XXXX,Seasonally,Fall 2024,WWTP 3,CAS,29796.30,...,46125.70,141.70,1172.45,223.34,281.19,30553.73,1849.30,393.36,1813.38,386035.6
4,Site 4,City 3,10/22/2024 0:00,Post_S4_5,Project XXXX,Seasonally,Fall 2024,WWTP 4,MBBR,72894.36,...,71903.66,1492.18,1267.70,266.83,363.03,2232.00,412.85,508.30,2296.57,326693.3

In [19]:
import numpy as np

# Standardize column names (remove spaces)
df.columns = df.columns.str.replace(" ", "_")

# Select concentration columns (11 to 52 exclude the last column total conc)
conc_cols = df.columns[10:-1]

# STEP 1: Remove rows where ALL concentration values are missing
df = df[df[conc_cols].notna().any(axis=1)]

# STEP 2: Remove rows with negative values in ANY compound
df = df[(df[conc_cols] >= 0).all(axis=1)]

# STEP 3: Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# STEP 4: Remove rows with invalid dates
df = df[df["Date"].notna()]

df.head()

,WWTP_/_Env.,Municipality,Date,Sampling_Point,Project,Monitoring_Interval,Season,WWTP,Tech_type,PE,...,Sucralose,Sulfapyridine,Telmisartan,Tramadol,Trimetoprim,Valsartan,Valsartan_acid,Venlafaxine,Venlafaxine_O-desmethyl,Total_Concentration_ngL
0,Site 1,City 1,2024-10-04,CAS_S1_5,Project XXXX,Seasonally,Fall 2024,WWTP 1A,CAS,21480.46,...,45860.97,2452.33,2026.55,114.35,349.61,4770.29,77.81,655.26,1369.85,298065.0
1,Site 1,City 1,2024-10-30,MBR_S1_7,Project XXXX,Seasonally,Fall 2024,WWTP 1B,MBR,80391.15,...,54066.31,661.41,2089.36,312.34,269.15,12647.16,1283.40,512.79,1139.59,173127.7
2,Site 2,City 2,2024-11-05,Post_S2_5,Project XXXX,Seasonally,Fall 2024,WWTP 2,CAS,12607.66,...,48321.51,2198.68,1599.23,347.75,382.38,3290.60,1229.50,440.15,2203.82,247389.0
3,Site 3,City 3,2024-11-12,Post_S3_5,Project XXXX,Seasonally,Fall 2024,WWTP 3,CAS,29796.30,...,46125.70,141.70,1172.45,223.34,281.19,30553.73,1849.30,393.36,1813.38,386035.6
4,Site 4,City 3,2024-10-22,Post_S4_5,Project XXXX,Seasonally,Fall 2024,WWTP 4,MBBR,72894.36,...,71903.66,1492.18,1267.70,266.83,363.03,2232.00,412.85,508.30,2296.57,326693.3

In [20]:
from pathlib import Path

# Define processed directory (same as SE2)
analysis_dir = Path.home() / "data" / "processed"
analysis_dir.mkdir(parents=True, exist_ok=True)

# Define output file
processed_file = analysis_dir/"analysis_ready_MPs_data.csv"

# Save dataframe
df.to_csv(processed_file, index=False)

processed_file

PosixPath('/home/jovyan/data/processed/analysis_ready_MPs_data.csv')